/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto1lenguajes.frames;

import com.mycompany.proyecto1lenguajes.AlmacenadorReportes.*;
import com.mycompany.proyecto1lenguajes.Automatas.Identificador;
import static com.mycompany.proyecto1lenguajes.Controladores.MovilizadorDatos.movilizar;
import com.mycompany.proyecto1lenguajes.Archivos.CargaArchivo;
import com.mycompany.proyecto1lenguajes.Archivos.ExportarArchivo;
import com.mycompany.proyecto1lenguajes.Automatas.Agrupacion;
import com.mycompany.proyecto1lenguajes.Automatas.NumeroDecimal;
import com.mycompany.proyecto1lenguajes.Automatas.Operador;
import com.mycompany.proyecto1lenguajes.Automatas.Puntuacion;
import com.mycompany.proyecto1lenguajes.CargadorObjetos.*;
import com.mycompany.proyecto1lenguajes.Controladores.CodigoCondicionalRepetidoAutomata;
import static com.mycompany.proyecto1lenguajes.Controladores.DatosInstanciadores.instanciadores;
import com.mycompany.proyecto1lenguajes.RegistroTablas.*;
import com.mycompany.proyecto1lenguajes.RegistroTablas.ReporteErrores;
import static com.mycompany.proyecto1lenguajes.frames.BusquedaCadena.resultadoBusqueda;
import static com.mycompany.proyecto1lenguajes.frames.RecuperacionErrores.recuperacionErrores;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Mariano
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static CargarError cargarError;//creamos carga error
    public static CargarLexema cargarLexema;//creamos carga lexema
    public static CargarToken cargarToken;//creamos carga token
    public static ArrayList<ReporteErrorObjeto> errorEstablecido;//indicamos un array list de error para leer los archivos
    public static ArrayList<RecuentoLexemaObjeto> lexemaEstablecido;//indicamos un array list de lexema para leer los archivos
    public static ArrayList<ReporteTokensObjeto> tokenEstablecido;//indicamos un array list de token para leer los archivos
    public Inicio() {
        initComponents();//iniciar componentes
        crearReportes();//llamado metodo crear reportes
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }
    //Creamos metodo para crear cargas
    public void crearReportes(){
        this.cargarError = new CargarError();  
        this.cargarLexema = new CargarLexema();
        this.cargarToken = new CargarToken();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CargaArchivo = new javax.swing.JTextArea();
        cargarArchivo = new javax.swing.JButton();
        analizarTexto = new javax.swing.JButton();
        buscarCadena = new javax.swing.JButton();
        buscarText = new javax.swing.JTextField();
        guardarArchivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MovimientoEstado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReportToken = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        RecuentoLexema = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        ReporteError = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buscarCadena1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reportes de tokens");

        CargaArchivo.setColumns(20);
        CargaArchivo.setRows(5);
        jScrollPane1.setViewportView(CargaArchivo);

        cargarArchivo.setBackground(new java.awt.Color(255, 255, 102));
        cargarArchivo.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        cargarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        cargarArchivo.setText("Cargar Archivo");
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });

        analizarTexto.setBackground(new java.awt.Color(0, 102, 255));
        analizarTexto.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        analizarTexto.setForeground(new java.awt.Color(0, 0, 0));
        analizarTexto.setText("ANALIZAR TEXTO");
        analizarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarTextoActionPerformed(evt);
            }
        });

        buscarCadena.setBackground(new java.awt.Color(0, 102, 255));
        buscarCadena.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        buscarCadena.setForeground(new java.awt.Color(0, 0, 0));
        buscarCadena.setText("Buscar cadena");
        buscarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCadenaActionPerformed(evt);
            }
        });

        guardarArchivo.setBackground(new java.awt.Color(255, 51, 51));
        guardarArchivo.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        guardarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        guardarArchivo.setText("Guardar Archivo");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });

        MovimientoEstado.setColumns(20);
        MovimientoEstado.setRows(5);
        jScrollPane2.setViewportView(MovimientoEstado);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mariano");

        ReportToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Token", "Lexema", "Fila", "Columna"
            }
        ));
        jScrollPane3.setViewportView(ReportToken);

        RecuentoLexema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lexema", "Token", "Cantidad"
            }
        ));
        jScrollPane4.setViewportView(RecuentoLexema);

        ReporteError.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cadena error", "Fila", "Columna"
            }
        ));
        jScrollPane6.setViewportView(ReporteError);

        jLabel5.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Texto Cargado");

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Movimiento de estado");

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reporte de errores");

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Recuento de lexemas");

        buscarCadena1.setBackground(new java.awt.Color(0, 102, 255));
        buscarCadena1.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        buscarCadena1.setForeground(new java.awt.Color(0, 0, 0));
        buscarCadena1.setText("ver rrecuperación de errores");
        buscarCadena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCadena1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel7)
                .addGap(233, 233, 233)
                .addComponent(jLabel8)
                .addGap(354, 354, 354)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(buscarCadena1)
                .addGap(937, 937, 937)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cargarArchivo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5)
                        .addGap(481, 481, 481)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(guardarArchivo)
                        .addGap(40, 40, 40)
                        .addComponent(analizarTexto)
                        .addGap(180, 180, 180)
                        .addComponent(buscarCadena)
                        .addGap(35, 35, 35)
                        .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cargarArchivo)
                        .addComponent(guardarArchivo)
                        .addComponent(analizarTexto))
                    .addComponent(buscarCadena)
                    .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCadena1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        //filechooser para abrir o guardar archivos
        JFileChooser archivoEleccion = new JFileChooser();
        int eleccion = archivoEleccion.showOpenDialog(this);//variable para seleccionar
        //aprove option es si el usuario le da en aceptar
        if (eleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = archivoEleccion.getSelectedFile();//seleccionamos file para fileReader, agarramos el seleccionado
            try {
                //llamos la clase carga archivo e ingresamos parametros
                CargaArchivo carga = new CargaArchivo();
                carga.leer(archivo, CargaArchivo);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer carga de archivo");
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void analizarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarTextoActionPerformed
        inicializadorValores();//método inicializador de valores
        //creamos variables
        String linea,reduccionLinea;
        String texto=CargaArchivo.getText();
        int contador=0;
        int verificadorEspacio=0,eliminadorWhile=1;
        char verificadorLinea;
        //convertimos el texto para lectura
        Reader leer = new StringReader(texto);
        BufferedReader leerTA = new BufferedReader(leer);
        try {
            //mientras existe linea leerá
            while ((linea = leerTA.readLine()) != null) {
                //reseteamos componentes de datos
                contador++;
                verificadorEspacio=0;
                eliminadorWhile=1;
                movilizar.setFila(contador);
                movilizar.setColumna(0);
                movilizar.setCaracteresUsados(0);
                movilizar.setCadenaUsada("");
                verificadorLinea=linea.charAt(0);//obtenemos valor valor posicion 0 de linea
                String comprobarPunto=Character.toString(verificadorLinea);//pasamos char a string 
                //si es letra ingresa a automata identificador 
                if(Character.isLetter(verificadorLinea)){
                    Identificador.identificadorInicio(linea,MovimientoEstado);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                    }
                }//Si es digito ingresamos a posibilidad de numero o digito
                else if(Character.isDigit(verificadorLinea)){
                    NumeroDecimal.numeroDecimalInicio(linea,MovimientoEstado);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                    }
                }//Si es +-*/ entre signos parecidos significa que entra a operacion
                else if(comprobarPunto.equals("+")|comprobarPunto.equals("-")|comprobarPunto.equals("*")|comprobarPunto.equals("/")|comprobarPunto.equals("%")){
                    Operador.operadorInicio(linea,MovimientoEstado);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                    }  
                }//si es . , ; entre signos parecidos significa que entra a puntuacion 
                else if(comprobarPunto.equals(".")|comprobarPunto.equals(",")|comprobarPunto.equals(";")|comprobarPunto.equals(".")){
                    Puntuacion.puntuacionInicio(linea,MovimientoEstado);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                    }
                }//si es ( ) [ { entre signos parecidos significa que entramos a agrupacion
                else if(comprobarPunto.equals("(")|comprobarPunto.equals(")")|comprobarPunto.equals("[")|comprobarPunto.equals("]")|comprobarPunto.equals("{")|comprobarPunto.equals("}")){
                    Agrupacion.agrupacionInicio(linea,MovimientoEstado);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                    }
                }else{
                    try {
                        //cargamos reporte de error
                        movilizar.setCadenaUsada(Character.toString(verificadorLinea));
                        movilizar.setCaracteresUsados(1);
                        cargarError.cargarReporte();
                        movilizar.setCondiconalError(1);
                        reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                        pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                        //señalizaos error
                        MovimientoEstado.setText(MovimientoEstado.getText()+"------------Error------------ al usar "+movilizar.getCadenaUsada()+"\n");
                        while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                            CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados(), MovimientoEstado);
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }             
            }
            if(movilizar.getCondiconalError()==1){
                //si hay error solo carga esta tabla
                ReporteErrores.completarTabla(errorEstablecido, ReporteError);
            }else if(movilizar.getCondiconalError()==0){
                //si no hay errores cargamos las tablas correctas
                RecuentoLexemas.completarTabla(lexemaEstablecido, RecuentoLexema);
                ReporteTokens.completarTabla(tokenEstablecido, ReportToken);
            }
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_analizarTextoActionPerformed
    private void inicializadorValores(){
        //creamos array list para reportes
        errorEstablecido = new ArrayList<>();  
        lexemaEstablecido = new ArrayList<>();   
        tokenEstablecido = new ArrayList<>(); 
        //llamamos a que se complete la tabla 
        ReporteErrores.completarTabla(errorEstablecido, ReporteError);
        RecuentoLexemas.completarTabla(lexemaEstablecido, RecuentoLexema);
        ReporteTokens.completarTabla(tokenEstablecido, ReportToken);
        //reiniciamos valores
        movilizar.setCondiconalError(0);
        MovimientoEstado.setText("");
        movilizar.setCaracteresUsados(0);
        movilizar.setCadenaUsada("");
        movilizar.setFila(0);
        movilizar.setColumna(0);
        recuperacionErrores.setText("");
        movilizar.setCadenaError("");
    }
    public void pasadorDatos(String linea, String reduccionLinea, char verificadorLinea){
        //llamamos a instanciadores para que se modifiquen según sea el caso solo pasando parametros
        instanciadores.setLinea(linea);
        instanciadores.setReduccionLinea(reduccionLinea);
        instanciadores.setVerificadorLinea(verificadorLinea);
    }
    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        ExportarArchivo.exportarArchivo(CargaArchivo);//enviamos parametro para guardar archivo texto
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void buscarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCadenaActionPerformed
        String valorBusqueda,textoArea,almacenadorPalabra;//creamos variables      
        valorBusqueda= buscarText.getText();//llamamos texto de entrada
        int localizador=0,interruptor=0;
        if (valorBusqueda.length() >= 1) {
            //pintamos dando luz a la letra
            DefaultHighlighter.DefaultHighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.RED);
            //indicamos a que es lo que daríamos luz
            textoArea=CargaArchivo.getText();//pasamos a string el texto
            resultadoBusqueda.setText(textoArea);
            Highlighter h = resultadoBusqueda.getHighlighter();
            h.removeAllHighlights();//removemos todas las luces que tiene
            
            for (int i = 0; i < textoArea.length(); i++) {//indicamos que si lea todas las letras del text area
                if(textoArea.charAt(i)==valorBusqueda.charAt(0)){//si contiene el primer caracter continua
                    //reiniciamos valores
                    almacenadorPalabra="";
                    localizador=i;
                    interruptor=textoArea.length()-i;//interruptor para que no siga repitiendo la secuencia si no cuenta con suficientes caracteres al final
                    for (int j = 0; j < valorBusqueda.length(); j++) {
                        
                        if(textoArea.charAt(i)==valorBusqueda.charAt(j)&&interruptor>=valorBusqueda.length()){ //verificamos que todos los siguientes caracteres coincidan
                            almacenadorPalabra=almacenadorPalabra+Character.toString(valorBusqueda.charAt(j));
                            if (valorBusqueda.equals(almacenadorPalabra)) {
                                //si cumple con que todos los caracteres sean iguales pintamos todo el texto buscado de lo contrario no
                                try {
                                    h.addHighlight(localizador, localizador+valorBusqueda.length(), highlightPainter);
                                } catch (BadLocationException ex) {
                                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                            i++;
                        }else{
                            j=valorBusqueda.length();
                        }
                    }
                }
            }
            BusquedaCadena.visible();//hacemos visible la busqueda de cadena
        } else {
            //indicamos mensaje de error
            JOptionPane.showMessageDialog(null, "Primero ingresa una cadena para ser leída");
        }
    }//GEN-LAST:event_buscarCadenaActionPerformed

    private void buscarCadena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCadena1ActionPerformed
        if (movilizar.getCondiconalError()==1) {
            RecuperacionErrores.visible(); //hacemos visible frame recuperacion errores
        }else{
            JOptionPane.showMessageDialog(null, "No hay errores en el último análisis");//identificamos que no surgieron errores
        }
    }//GEN-LAST:event_buscarCadena1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea CargaArchivo;
    public static javax.swing.JTextArea MovimientoEstado;
    public static javax.swing.JTable RecuentoLexema;
    public static javax.swing.JTable ReportToken;
    public static javax.swing.JTable ReporteError;
    private javax.swing.JButton analizarTexto;
    private javax.swing.JButton buscarCadena;
    private javax.swing.JButton buscarCadena1;
    private javax.swing.JTextField buscarText;
    private javax.swing.JButton cargarArchivo;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
