/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectoFinallenguajes.frames;

import com.mycompany.proyectoFinallenguajes.AlmacenadorReportes.ReporteErrorObjeto;
import com.mycompany.proyectoFinallenguajes.AlmacenadorReportes.ReporteTokensObjeto;
import com.mycompany.proyectoFinallenguajes.CargadorObjetos.CargarError;
import com.mycompany.proyectoFinallenguajes.CargadorObjetos.CargarToken;
import com.mycompany.proyectoFinallenguajes.RegistroTablas.ReporteTokens;
import static com.mycompany.proyectoFinallenguajes.Controladores.MovilizadorDatos.movilizar;
import com.mycompany.proyectoFinallenguajes.Archivos.CargaArchivo;
import com.mycompany.proyectoFinallenguajes.Archivos.ExportarArchivo;
import com.mycompany.proyectoFinallenguajes.Archivos.ReescribirArchivo;
import com.mycompany.proyectoFinallenguajes.Automatas.Identificador;
import com.mycompany.proyectoFinallenguajes.Automatas.Literal;
import com.mycompany.proyectoFinallenguajes.Automatas.Numero;
import com.mycompany.proyectoFinallenguajes.Controladores.CodigoCondicionalRepetidoAutomata;
import static com.mycompany.proyectoFinallenguajes.Controladores.DatosInstanciadores.instanciadores;
import com.mycompany.proyectoFinallenguajes.RegistroTablas.ReporteErrores;
import static com.mycompany.proyectoFinallenguajes.frames.BusquedaCadena.resultadoBusqueda;
import static com.mycompany.proyectoFinallenguajes.frames.RecuperacionErrores.recuperacionErrores;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Mariano
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static CargarError cargarError;//creamos carga error
    public static CargarToken cargarToken;//creamos carga token
    public static ArrayList<ReporteErrorObjeto> errorEstablecido;//indicamos un array list de error para leer los archivos
    public static ArrayList<ReporteTokensObjeto> tokenEstablecido;//indicamos un array list de token para leer los archivos
    protected UndoManager manager = new UndoManager();
    public Inicio() {
        initComponents();//iniciar componentes
        crearReportes();//llamado metodo crear reportes
        CargaArchivo.getDocument().addUndoableEditListener(manager);
        this.setLocationRelativeTo(null);//Centramos nuestro frame
        estancia(filaA,columnaA,CargaArchivo);
        estancia(filaA1,columnaA1,Prcesado);
    }
    //Creamos metodo para crear cargas
    public void crearReportes(){
        this.cargarError = new CargarError();  
        this.cargarToken = new CargarToken();
        
    }
    public void abrirArchivo(){
        //filechooser para abrir o guardar archivos
        JFileChooser archivoEleccion = new JFileChooser();
        int eleccion = archivoEleccion.showOpenDialog(this);//variable para seleccionar
        //aprove option es si el usuario le da en aceptar
        if (eleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = archivoEleccion.getSelectedFile();//seleccionamos file para fileReader, agarramos el seleccionado
            movilizar.setDirectorio(archivo.getPath());
            try {
                //llamos la clase carga archivo e ingresamos parametros
                CargaArchivo.setText("");
                CargaArchivo carga = new CargaArchivo();
                carga.leer(archivo, CargaArchivo);
                CargaArchivo.setText(CargaArchivo.getText().substring(0,CargaArchivo.getText().length()-1));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer carga de archivo");
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        analizarTexto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CargaArchivo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        buscarText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        columnaA = new javax.swing.JLabel();
        filaA = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        columnaA1 = new javax.swing.JLabel();
        filaA1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Prcesado = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReportToken = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ReporteError = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirArchivo = new javax.swing.JMenuItem();
        nuevoArchivo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        exportar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        copiar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        deshacer = new javax.swing.JMenuItem();
        rehacer = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        acercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador USAC");

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));

        analizarTexto.setBackground(new java.awt.Color(0, 255, 0));
        analizarTexto.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        analizarTexto.setForeground(new java.awt.Color(0, 0, 0));
        analizarTexto.setText("ANALIZAR TEXTO");
        analizarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarTextoActionPerformed(evt);
            }
        });

        CargaArchivo.setColumns(20);
        CargaArchivo.setRows(5);
        jScrollPane1.setViewportView(CargaArchivo);

        jLabel5.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Texto Cargado");

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Busqueda");

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        columnaA.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        columnaA.setForeground(new java.awt.Color(0, 0, 0));
        columnaA.setText("Columna actual: 1");

        filaA.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        filaA.setForeground(new java.awt.Color(0, 0, 0));
        filaA.setText("Fila actual: 1");

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Información texto cargado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(filaA))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(columnaA)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filaA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnaA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("C");

        jLabel11.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("S");

        jLabel12.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("A");

        jLabel10.setFont(new java.awt.Font("Engravers MT", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("U");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(3, 3, 3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));

        columnaA1.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        columnaA1.setForeground(new java.awt.Color(0, 0, 0));
        columnaA1.setText("Columna actual: 1");

        filaA1.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        filaA1.setForeground(new java.awt.Color(0, 0, 0));
        filaA1.setText("Fila actual: 1");

        jLabel13.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Información texto procesado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(filaA1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(columnaA1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filaA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnaA1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Prcesado.setColumns(20);
        Prcesado.setRows(5);
        jScrollPane2.setViewportView(Prcesado);

        jLabel14.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Texto Procesado");

        jDesktopPane1.setLayer(analizarTexto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buscarText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(analizarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(359, 359, 359))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(361, 361, 361))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(buscarText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(analizarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        jTabbedPane1.addTab("Procesamiento de datos", jDesktopPane1);

        jDesktopPane2.setBackground(new java.awt.Color(153, 255, 255));

        ReportToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Token", "Lexema", "Fila", "Columna"
            }
        ));
        jScrollPane3.setViewportView(ReportToken);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reportes de tokens");

        ReporteError.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cadena error", "Fila", "Columna"
            }
        ));
        jScrollPane6.setViewportView(ReporteError);

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reporte de errores");

        jDesktopPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(239, 239, 239))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jDesktopPane2);

        jMenu1.setText("Abrir");

        abrirArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrirArchivo.setText("Abrir Archivo");
        abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivo);

        nuevoArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nuevoArchivo.setText("Nuevo Archivo");
        nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoArchivo);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Guardar");

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu3.add(guardar);

        guardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        guardarComo.setText("Guardar Como");
        guardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComoActionPerformed(evt);
            }
        });
        jMenu3.add(guardarComo);

        exportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportar.setText("Exportar Texto Procesado");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        jMenu3.add(exportar);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Herramientas");

        copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jMenu2.add(copiar);

        pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        pegar.setText("Pegar");
        pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarActionPerformed(evt);
            }
        });
        jMenu2.add(pegar);

        deshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deshacer.setText("Deshacer");
        deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerActionPerformed(evt);
            }
        });
        jMenu2.add(deshacer);

        rehacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        rehacer.setText("Rehacer");
        rehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehacerActionPerformed(evt);
            }
        });
        jMenu2.add(rehacer);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Buscar Cadena");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Información");

        acercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        acercaDe.setText("Acerca de Analizador USAC");
        acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeActionPerformed(evt);
            }
        });
        jMenu5.add(acercaDe);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializadorValores(){
        //creamos array list para reportes
        errorEstablecido = new ArrayList<>();     
        tokenEstablecido = new ArrayList<>(); 
        //llamamos a que se complete la tabla 
        ReporteErrores.completarTabla(errorEstablecido, ReporteError);
        ReporteTokens.completarTabla(tokenEstablecido, ReportToken);
        //reiniciamos valores
        movilizar.setCondiconalError(0);
        movilizar.setCaracteresUsados(0);
        movilizar.setCadenaUsada("");
        movilizar.setFila(0);
        movilizar.setColumna(0);
        recuperacionErrores.setText("");
        movilizar.setCadenaError("");
    }
    public void pasadorDatos(String linea, String reduccionLinea, char verificadorLinea){
        //llamamos a instanciadores para que se modifiquen según sea el caso solo pasando parametros
        instanciadores.setLinea(linea);
        instanciadores.setReduccionLinea(reduccionLinea);
        instanciadores.setVerificadorLinea(verificadorLinea);
    }
    private void abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoActionPerformed
        if(movilizar.getDirectorio().length()==0&&CargaArchivo.getText().length()>0){
            JOptionPane.showMessageDialog(null, "Tienes un archivo sin guardar, si cargas uno se perderá");
            abrirArchivo();
        }else if(movilizar.getDirectorio().length()>0){
            FileReader leerA = null;
            try {
                leerA = new FileReader(movilizar.getDirectorio()); //ingresamos archivo
                BufferedReader leerTA = new BufferedReader(leerA);//lector del archivo}
                String archivoLeido= leerTA.lines().collect(Collectors.joining());//leer string
                if(archivoLeido.equals(CargaArchivo.getText())){
                    abrirArchivo();
                }else{
                    JOptionPane.showMessageDialog(null, "Tienes un archivo sin guardar, si cargas uno se perderá");
                    abrirArchivo();
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    leerA.close();
                } catch (IOException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            abrirArchivo();
        }
        
    }//GEN-LAST:event_abrirArchivoActionPerformed

    private void nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchivoActionPerformed
        if(movilizar.getDirectorio().length()==0&&CargaArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Ya está en un nuevo archivo");
        }else if(movilizar.getDirectorio().length()==0&&CargaArchivo.getText().length()>0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VerificarCambios().setVisible(true);
                        }
                    });
        }
            else{
            FileReader leerA = null;
            try {
                leerA = new FileReader(movilizar.getDirectorio()); //ingresamos archivo
                BufferedReader leerTA = new BufferedReader(leerA);//lector del archivo}
                String archivoLeido= leerTA.lines().collect(Collectors.joining());//leer string
                if(archivoLeido.equals(CargaArchivo.getText())){
                    
                    CargaArchivo.setText("");
                    movilizar.setDirectorio("");
                }else{
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VerificarCambios().setVisible(true);
                        }
                    });
                }
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    leerA.close();
                } catch (IOException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_nuevoArchivoActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
        CargaArchivo.copy();
    }//GEN-LAST:event_copiarActionPerformed

    private void deshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshacerActionPerformed
        try {
          manager.undo();
        } catch (CannotRedoException cre) {
          cre.printStackTrace();
        }
      
    }//GEN-LAST:event_deshacerActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        ReescribirArchivo.reescribir(CargaArchivo);
    }//GEN-LAST:event_guardarActionPerformed

    private void rehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehacerActionPerformed
         try {
          manager.redo();
        } catch (CannotRedoException cre) {
          cre.printStackTrace();
        }
    }//GEN-LAST:event_rehacerActionPerformed

    private void guardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComoActionPerformed
        ExportarArchivo.exportarArchivo(CargaArchivo);//enviamos parametro para guardar archivo texto
    }//GEN-LAST:event_guardarComoActionPerformed

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
        CargaArchivo.paste();
    }//GEN-LAST:event_pegarActionPerformed

    private void acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreadorInformacion().setVisible(true);
            }
        });
    }//GEN-LAST:event_acercaDeActionPerformed
    public void estancia(JLabel filaA,JLabel columnaA,JTextArea carga){
        carga.addCaretListener(new CaretListener() {//para ver la posicion
            @Override
            public void caretUpdate(CaretEvent e) {//caret es para verificar si hay cambio click
                JTextArea editar = (JTextArea) e.getSource();
                int filaActual = 1,columnaReciente=1;
                try {
                    int caretpos = editar.getCaretPosition();// editamos el área
                    filaActual = editar.getLineOfOffset(caretpos);
                    //columna debe ser 1 al inicio
                    columnaReciente = caretpos - editar.getLineStartOffset(filaActual)+1;
                    filaActual += 1;//cuando avance un se le sumara uno a la linea
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }

                //reevisamos nuevamente
                filaA.setText("FILA ACTUAL: "+filaActual);
                columnaA.setText("COLUMNA ACTUAL: "+columnaReciente);
            }
        });
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String valorBusqueda,textoArea,almacenadorPalabra;//creamos variables      
        valorBusqueda= buscarText.getText();//llamamos texto de entrada
        int localizador=0,interruptor=0;
        if (valorBusqueda.length() >= 1) {
            //pintamos dando luz a la letra
            DefaultHighlighter.DefaultHighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(Color.RED);
            //indicamos a que es lo que daríamos luz
            textoArea=CargaArchivo.getText();//pasamos a string el texto
            resultadoBusqueda.setText(textoArea);
            Highlighter h = resultadoBusqueda.getHighlighter();
            h.removeAllHighlights();//removemos todas las luces que tiene
            
            for (int i = 0; i < textoArea.length(); i++) {//indicamos que si lea todas las letras del text area
                if(textoArea.charAt(i)==valorBusqueda.charAt(0)){//si contiene el primer caracter continua
                    //reiniciamos valores
                    almacenadorPalabra="";
                    localizador=i;
                    interruptor=textoArea.length()-i;//interruptor para que no siga repitiendo la secuencia si no cuenta con suficientes caracteres al final
                    for (int j = 0; j < valorBusqueda.length(); j++) {
                        
                        if(textoArea.charAt(i)==valorBusqueda.charAt(j)&&interruptor>=valorBusqueda.length()){ //verificamos que todos los siguientes caracteres coincidan
                            almacenadorPalabra=almacenadorPalabra+Character.toString(valorBusqueda.charAt(j));
                            if (valorBusqueda.equals(almacenadorPalabra)) {
                                //si cumple con que todos los caracteres sean iguales pintamos todo el texto buscado de lo contrario no
                                try {
                                    h.addHighlight(localizador, localizador+valorBusqueda.length(), highlightPainter);
                                } catch (BadLocationException ex) {
                                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                            i++;
                        }else{
                            j=valorBusqueda.length();
                        }
                    }
                }
            }
            BusquedaCadena.visible();//hacemos visible la busqueda de cadena
        } else {
            //indicamos mensaje de error
            JOptionPane.showMessageDialog(null, "Primero ingresa una cadena para ser leída");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void analizarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarTextoActionPerformed
        inicializadorValores();//método inicializador de valores
        //creamos variables
        String linea,reduccionLinea;
        String texto=CargaArchivo.getText();
        int contador=0;
        char verificadorLinea;
        String comprobarVerificador;
        char guionMedio = '-';
        //convertimos el texto para lectura
        Reader leer = new StringReader(texto);
        BufferedReader leerTA = new BufferedReader(leer);
        try {
            //mientras existe linea leerá
            while ((linea = leerTA.readLine()) != null) {
                //reseteamos componentes de datos
                contador++;
                movilizar.setFila(contador);
                movilizar.setColumna(0);
                movilizar.setCaracteresUsados(0);
                movilizar.setCadenaUsada("");
                verificadorLinea=linea.charAt(0);//obtenemos valor valor posicion 0 de linea
                //si es letra ingresa a automata identificador
                comprobarVerificador=Character.toString(verificadorLinea);//pasamos char a string
                if(Character.isLetter(verificadorLinea)|comprobarVerificador.equals("_")){
                    Identificador.identificadorInicio(linea);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados());
                    }
                }//Si es digito ingresamos a posibilidad de numero positivo o negativo
                else if((Character.isDigit(verificadorLinea)|(guionMedio==verificadorLinea&&linea.length()>1))){
                    Numero.numeroInicio(linea);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados());
                    }
                }else if(comprobarVerificador.equals("/")){
                    if(linea.length()>1){
                        verificadorLinea=linea.charAt(1);//obtenemos valor valor posicion 1 de linea
                        comprobarVerificador=Character.toString(verificadorLinea);
                        if(comprobarVerificador.equals("/")){
                            movilizar.setTokenProviniente("Comentario");
                            try {
                                movilizar.setCaracteresUsados(linea.length());
                                movilizar.setColumna(1);
                                movilizar.setCadenaUsada(linea);
                                cargarToken.cargarToken();
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                }else if(comprobarVerificador.equals("\""  )){
                    Literal.literalInicio(linea);
                    reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                    pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                    while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                        CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados());
                    }
                }
                //Si es +-*/ entre signos parecidos significa que entra a operacion
                else{
                    try {
                        //cargamos reporte de error
                        movilizar.setCadenaUsada(Character.toString(verificadorLinea));
                        movilizar.setCaracteresUsados(1);
                        cargarError.cargarReporte();
                        movilizar.setCondiconalError(1);
                        reduccionLinea=linea.substring(movilizar.getCaracteresUsados(), linea.length());
                        pasadorDatos(linea,reduccionLinea,verificadorLinea);//sirve para enviar datos a instanciador de repitencia
                        //señalizaos error

                        while(movilizar.getCaracteresUsados()<linea.length()){//repetimos instancia de automatas
                            CodigoCondicionalRepetidoAutomata.codigoAutomataRepitencia(instanciadores.getLinea(), instanciadores.getVerificadorLinea(), instanciadores.getReduccionLinea(), movilizar.getCaracteresUsados());
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            if(movilizar.getCondiconalError()==1){
                //si hay error solo carga esta tabla
                ReporteErrores.completarTabla(errorEstablecido, ReporteError);
            }else if(movilizar.getCondiconalError()==0){
                //si no hay errores cargamos las tablas correctas
                ReporteTokens.completarTabla(tokenEstablecido, ReportToken);
            }
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_analizarTextoActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        if(Prcesado.getText().length()==0){
           JOptionPane.showMessageDialog(null, "No hay texo interno en el apartado de procesado");
        }else{
            ExportarArchivo.exportarArchivo(Prcesado);//enviamos parametro para guardar archivo texto 
        }
    }//GEN-LAST:event_exportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea CargaArchivo;
    public static javax.swing.JTextArea Prcesado;
    public static javax.swing.JTable ReportToken;
    public static javax.swing.JTable ReporteError;
    private javax.swing.JMenuItem abrirArchivo;
    private javax.swing.JMenuItem acercaDe;
    private javax.swing.JButton analizarTexto;
    private javax.swing.JTextField buscarText;
    private javax.swing.JLabel columnaA;
    private javax.swing.JLabel columnaA1;
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem deshacer;
    private javax.swing.JMenuItem exportar;
    private javax.swing.JLabel filaA;
    private javax.swing.JLabel filaA1;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem nuevoArchivo;
    private javax.swing.JMenuItem pegar;
    private javax.swing.JMenuItem rehacer;
    // End of variables declaration//GEN-END:variables
}
